spring.application.name=m-motors-app
# JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false

# Database
spring.datasource.url=${DATABASE_URL}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# Upload
spring.servlet.multipart.max-file-size=5MB
spring.servlet.multipart.max-request-size=25MB
spring.servlet.multipart.enabled=true

# Upload directory (Heroku filesystem)
app.upload.dir=/tmp/mmotors/uploads

# Admin email
app.admin.email=${ADMIN_EMAIL:admin@mmotors.fr}

spring.mail.from=${MAIL_FROM:admin@mmotors.fr}
# Mail Mailjet
spring.mail.host=${MAIL_HOST}
spring.mail.port=${MAIL_PORT}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true